project:
  type: website

website:
  title: "Atelierul lui Vlad"
  favicon: images/logo3.png  # Use the light logo as the favicon
  navbar: false


format:
  html:
    theme: flatly
    css: _site/styles.css  # Link to custom CSS file
    smooth-scroll: true  # Enable smooth scrolling